os:
  - linux

sudo: required
language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y

install:
  - pecl install libsodium
  # Add box to allow the my127ws phar to be built
  - wget https://github.com/humbug/box/releases/download/3.6.0/box.phar && chmod +x box.phar && sudo mv box.phar /usr/local/bin/box
  - composer install

script:
  - composer test
  - find . -type f ! -path "./.git/*" ! -path "./bin/workspace" ! -path "./bin/build" ! -path "./vendor/*" ! -name "*.phar" ! -name "*.php" -and \( -name "*.sh" -or -perm -0111 \) -exec shellcheck --exclude=SC1008,SC1091 {} +
