name: "CI"

on:
    pull_request:
        branches: 
            - '0.2.x'
    push:
        branches:
            - '0.2.x'

env:
    fail-fast: true
    TZ: "Europe/Paris"

jobs:
    phpunit:
        name: "PHPUnit (${{ matrix.php-version }})"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - '7.3'
                    - '7.4'
                    - '8.0'

        steps:
            -
                name: "Checkout code"
                uses: "actions/checkout@v2"
            -
                name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "none"
                    extensions: "${{ env.REQUIRED_PHP_EXTENSIONS }}"
                    php-version: "${{ matrix.php-version }}"
                    tools: composer:v2

            -
                name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--no-scripts"

            -
                name: "Run PHPUnit"
                run: "composer test"
